rvm: '2.2.1'
addons:
  postgresql: '9.4.1'
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql
  - sudo apt-get install -qq postgresql-server-dev-9.4.1
  - sudo apt-get install -qq libpq-dev
  - psql -c 'create database chitter_challenge_test;' -U postgres
script: bundle exec rspec spec